export const offsetByCity = {
  'Baker Island,Howland Island':-12,
  'Pago Pago,Alofi,Midway,Niue':-11,
  'Avarua,Papeete,Hawaii,Honolulu,Tahiti':-10,
  'Atuona,Marquesas':-9.5,
  'Rikitea,Atka':-9,
  'Adamstown,Alaska,Anchorage,Metlakatla':-8,
  'British Columbia,Surrey,Vancouver,Yukon,Culiacán,Tijuana,Arizona,California,Los Angeles,Nevada,Oregon,Phoenix,San Diego,San Francisco,San Jose,Santa Isabel,Dawson Creek,Fort Nelson,Phoenix,Whitehorse,Dawson':-7,
  'Belmopan,Alberta,Calgary,Edmonton,Northwest Territories,Nunavut,Saskatchewan,Limón San José,Puerto Ayora,San Salvador,Santa Ana,Guatemala City,San Pedro Sula,Tegucigalpa,Ciudad Neza,Ecatepec de Morelos,Guadalajara,León,Mexico City,Monterrey,Puebla City,León,Managua,Albuquerque,Colorado,Colorado Springs,Denver,El Paso,Idaho,Montana,New Mexico,Utah,Wyoming,Swift Current,Bahia Banderas,Tell City,Costa Rica,San Luis,El Salvador,Ciudad Juarez,Cambridge Bay,Ojinaga,Belize,Chihuahua':-6,
  'Acre,Rio Branco,Manitoba,Winnipeg,George Town,Barranquilla,Bogotá,Cali,Cartagena,Medellín,Guayaquil,Quito,Kingston,Spanish Town,Cancún,Ciudad Juárez,Panama City,Arequipa,Lima,Trujillo,Alabama,Arkansas,Austin,Chicago,Dallas,Fort Worth,Houston,Illinois,Iowa,Kansas,Kansas City,Louisiana,Memphis,Milwaukee,Minneapolis,Minnesota,Mississippi,Missouri,Nashville,Nebraska,North Dakota,Oklahoma,Oklahoma City,Omaha,San Antonio,South Dakota,Tennessee,Texas,Tulsa,Wisconsin,New Salem,Rio Branco,Grand Turk,Coral Harbour,Rankin Inlet,Rainy River,Porto Acre,Panama,Jamaica,Easter Island,Cayman Islands,Cancun,Bogota,Winnipeg':-5,
  "The Valley,St. John's,Oranjestad,Bridgetown,La Paz,Santa Cruz de la Sierra,Amazonas,Campo Grande,Manaus,Mato Grosso,Mato Grosso do Sul,Rondônia,Roraima,Road Town,Montreal,Ontario,Ottawa,Quebec,Toronto,Kralendijk,Havana,Santiago de Cuba,Willemstad,Roseau,Santiago de los Caballeros,Santo Domingo,St. George's,Basse-Terre,Georgetown,Port-au-Prince,Fort-de-France,Plymouth,Carolina,San Juan,Gustavia,Castries,Marigot,Basseterre,Kingstown,Nassau,Chaguanas,Port of Spain,Cockburn Town,Charlotte Amalie,Atlanta,Baltimore,Boston,Charlotte,Cincinnati,Cleveland,Columbus,Connecticut,Delaware,Detroit,Florida,Georgia,Indiana,Indianapolis,Jacksonville,Kentucky,Lexington-Fayette,Maine,Maryland,Massachusetts,Miami,Michigan,New Hampshire,New Jersey,New York,North Carolina,Ohio,Pennsylvania,Philadelphia,Pittsburgh,Raleigh,Rhode Island,South Carolina,Staten Island,Tampa,Vermont,Virginia,Virginia Beach,Washington D.C.,West Virginia,Caracas,Maracaibo,Maracay,Thunder Bay,Santo Domingo,Boa Vista,Lower Princes,Saint Martin,Glace Bay,Goose Bay,Fort Wayne,St Barthelemy,St Kitts,St Lucia,St Thomas,St Vincent,Porto Velho,Puerto Rico,Thule,Louisville,Guyana,Grenada,Dominica,Barbados,Antigua,Anguilla,Tortola,Vevay,Virgin,Blanc-Sablon,Guadeloupe,Winamac":-4,
  'Buenos Aires,Córdoba,Rosario,Hamilton,Alagoas,Amapá,Bahia,Belo Horizonte,Belém,Brasília,Ceará,Curitiba,Espírito Santo,Federal District,Fortaleza,Goiás,Maranhão,Minas Gerais,Paraná,Paraíba,Pará,Pernambuco,Piauí,Porto Alegre,Recife,Rio Grande do Norte,Rio Grande do Sul,Rio de Janeiro,Salvador,Santa Catarina,Sergipe,São Paulo,Tocantins,Halifax,New Brunswick,Nova Scotia,Prince Edward Island,Sydney,Puente Alto,Santiago,Stanley,Cayenne,Pituffik,Asunción,Ciudad del Este,Paramaribo,Montevideo,Salto,Bermuda,Falkland Islands,Palmer Station,Rothera Station,Sao Paulo,La Rioja,Rio Gallegos,Punta Arenas,Comodoro Rivadavia,Tucuman,Asuncion,Jujuy,Mendoza,Belem':-3,
  "St Johns":-3.5,
  "Newfoundland and Labrador,St. John's Canada":-2.5,
  'Saint-Pierre,Grytviken,South Georgia,Miquelon':-2,
  'Praia,Nuuk,Cape Verde':-1,
  'Bobo-Dioulasso,Ouagadougou,Accra,Kumasi,Conakry,Nzérékoré,Bafatá,Bissau,Reykjavik,Abidjan,Bouaké,Yamoussoukro,Monrovia,Bamako,Sikasso,Nouadhibou,Nouakchott,Jamestown,Dakar,Touba,Bo,Freetown,Banjul,Lomé,Sokodé,Azores,Troll Station,São Tomé,Sao Tome,Danmarkshavn,Lome':0,
  'GMT':0,
  "Algiers,Boumerdas,Oran,Luanda,N'dalatando,Abomey-Calavi,Porto-Novo,Douala,Yaoundé,Las Palmas,Bangui,Bimbo,Moundou,N'Djamena,Brazzaville,Pointe-Noire,Kikwit,Kinshasa,Bata,Malabo,Tórshavn,Libreville,Port-Gentil,Cork,Dublin,Casablanca,Rabat,Niamey,Aba,Abuja,Benin City,Ibadan,Kaduna,Kano,Lagos,Maiduguri,Port Harcourt,Zaria,Lisbon,Porto,Tunis,Birmingham,Bristol,Edinburgh,Glasgow,Leeds,Leicester,Liverpool,London,Manchester,Sheffield,Oxford,Canary Islands,Faroe Islands,Madeira,Isle of Man,El Aaiun,Belfast":1,
  'Durrës,Tirana,Graz,Vienna,Antwerp,Brussels,Sarajevo,Francistown,Gaborone,Bujumbura,Muyinga,Kisangani,Lubumbashi,Mbuji-Mayi,Zagreb,Brno,Prague,Aarhus,Copenhagen,Manzini,Mbabane,Lyon,Marseille,Nice,Paris,Toulouse,Berlin,Cologne,Essen,Frankfurt,Hamburg,Munich,Stuttgart,Budapest,Debrecen,Milan,Naples,Palermo,Rome,Turin,Pristina,Mafeteng,Maseru,Tripoli,Blantyre,Lilongwe,Valletta,Podgorica,Maputo,Matola,Rundu,Windhoek,Amsterdam,The Hague,Bitola,Skopje,Bergen,Oslo,Krakow,Lodz,Warsaw,Kaliningrad,Kigali,Belgrade,Niš,Bratislava,Košice,Ljubljana,Maribor,Cape Town,Durban,Johannesburg,Pretoria,Soweto,Juba,Malakal,Barcelona,Madrid,Seville,Valencia,Zaragoza,Kassala,Khartoum,Port Sudan,Gothenburg,Stockholm,Bern,Zurich,Kitwe,Lusaka,Bulawayo,Harare,Longyearbyen,Jan Mayen,San Marino,Vatican,Monaco,Malta,Luxembourg,Gibraltar,Cordoba,Andorra,Ceuta':2,
  "Manama,Gomel,Minsk,Mogilev,Plovdiv,Sofia,Moroni,Limassol,Nicosia,Djibouti,Alexandria,Cairo,Port Said,Asmara,Keren,Tallinn,Tartu,Adama,Addis Ababa,Bahir Dar,Dire Dawa,Mek'ele,Espoo,Helsinki,Athens,Thessaloniki,Baghdad,Basra,Haifa,Jerusalem,Amman,Zarqa,Mombasa,Nairobi,Nakuru,Al Ahmadi,Kuwait,Daugavpils,Riga,Beirut,Tripoli,Kaunas,Vilnius,Antananarivo,Toamasina,Mamoudzou,Chisinau,Tiraspol,Gaza,Doha,Bucharest,Iasi,Kazan,Moscow,Nizhny Novgorod,Rostov-on-Don,Saint Petersburg,Jeddah,Mecca,Riyadh,Mogadishu,Aleppo,Damascus,Dar es Salaam,Dodoma,Adana,Ankara,Bursa,Gaziantep,Istanbul,Izmir,Konya,Gulu,Kampala,Lira,Dnipro,Donetsk,Kharkiv,Kyiv,Odesa,Al Hudaydah,Sanaa,Mariehamn,Syowa Station,Comoro Islands,Tel Aviv,Asmera,Zaporozhye,Qatar,Kiev,Bahrain,Aden":3,
  'Isfahan,Karaj,Mashhad,Qom,Shiraz,Tabriz,Tehran':3.5,
  'Yerevan,Baku,Ganja,Kutaisi,Tbilisi,Port,Louis,Vacoas-Phoenix,Muscat,Seeb,Samara,Tolyatti,Saint-Denis,Victoria,Abu,Dhabi,Dubai,Mahé,Mauritius,Ulyanovsk':4,
  'Kabul,Kandahar,Mazari Sharif':4.5,
  'Almaty,Astana,Malé,Faisalabad,Gujranwala,Hyderābād,Islamabad,Karachi,Lahore,Multan,Peshawar,Quetta,Rawalpindi,Chelyabinsk,Yekaterinburg,Dushanbe,Khujand,Ashgabat,Turkmenabat,Namangan,Tashkent,Mawson Station,Kerguelen Islands,Male,Maldives,Samarkand':5,
  'Ahmedabad,Bengaluru,Chennai,Hyderabad,Kanpur,Kolkata,Mumbai,New Delhi,Pune,Surat,Colombo,Moratuwa,Bangalore,Mysore,Calcutta':5.5,
  'Biratnagar,Kathmandu,Katmandu,Pokhara':5.75,
  'Chittagong,Comilla,Cox’s Bāzār,Dhaka,Jessore,Khulna,Narsingdi,Rajshahi,Rangpur City,Tongi,Thimphu,Bishkek,Osh,Barnaul,Omsk,Vostok Station,Chagos Islands,Dacca,Thimphu,Thimbu':6,
  'Naypyidaw,Yangon,Rangoon,Cocos Islands':6.5,
  'Phnom Penh,Takeo,Bandung,Bekasi,Depok,Jakarta,Medan,Palembang,Semarang,South Tangerang,Surabaya,Tangerang,Pakse,Vientiane,Khovd,Krasnoyarsk,Novosibirsk,Bangkok,Chon Buri,Mueang Samut Prakan,Nonthaburi,Udon Thani,Biên Hòa,Da Nang,Haiphong,Hanoi,Ho Chi Minh City,Huế,Nha Trang,Davis Station,Christmas Islands,Saigon,Novokuznetsk,Pontianak':7,
  'Mandurah,Perth,Western Australia,Bandar Seri Begawan,Beijing,Chengdu,Chongqing,Dongguan,Guangzhou,Nanjing,Shanghai,Shenzhen,Tianjin,Wuhan,Banjarmasin,Makassar,Manado,Klang,Kota Bharu,Kuala Lumpur,Erdenet,Ulan Bator,Antipolo City,Bacolod City,Cebu City,Davao City,General Santos,Manila,Zamboanga City,Irkutsk,Kaohsiung,Taipei,Hangzhou,Casey Station,Ujung Pandang,Hong Kong,Macau,Macao,Urumqi,Ulan Bator,Singapore,Harbin,Kashgar,Chungking,Kuching,Brunei':8,
  'Eucla':8.75,
  'Ambon City,Jayapura,Osaka,Tokyo,Yokohama,Hamhung,Pyongyang,Chita,Yakutsk,Busan,Incheon,Seoul,Dili,Palau':9,
  'Darwin,Northern Territory,Adelaide':9.5,
  "Brisbane,Gold Coast,Queensland,Hagåtña,Weno,Lae,Port Moresby,Khabarovsk,Vladivostok,Lindeman Island,Dumont d'Urville Station,Saipan,Guam,Chuuk Island":10,
  'Adelaide Hills,Broken Hill NSW,South Australia,Yancowinna':10.5,
  'Canberra,Currie,New South Wales,Sydney,Tasmania,Victoria,Palikir,Noumea,Yuzhno-Sakhalinsk,Honiara,Port Vila,Lord Howe,Hobart,Melbourne,Macquarie Island Station,Sakhalin,Guadalcanal,Srednekolymsk':11,
  'Suva,Tarawa,Majuro,Kingston,Petropavlovsk-Kamchatsky,Mata-Utu,Funafuti,South Pole,Nauru,Fiji,Kwajalein,Kamchatka':12,
  "Auckland,Wellington,Apia,Nuku'alofa,McMurdo Station,Samoa,Kanton Island,Tongatapu":13,
  'Chatham':13.75,
  'Tabwakea Village':14,
}

//Time zone abbreviation
//GMT is currently not observed in the UK. See London for the time in the UK and London.
export const timeZoneAbbr ={
  'GMT':0,
  'BST':1,'IST':1,
  'WEST':1,'WET':1,
  'CEST':2,'CET':2,
  'EEST':3,'EET':3,'MSK':3,
  '+0330':3.5,
  '+04':4,'+05':5,'+06':6,'+07':7,'+08':8,'+0630':6.5,
  '+09':9,'+10':10,'+11':11,'+12':12,
  'NZDT':12,
  'PST':-8,
  'PDT':-7,
  'MST':-7,
  'MDT':-6,
  'CDT':-5,
  'EST':-5,
  'EDT':-4,
  'AST':-4,
  'ADT':-3,
  'UTC':0,
}

//https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
export const ianaTzCodeEast = {
  1:'Africa/Bangui',
  2:'Africa/Blantyre',
  3:'Africa/Asmara',
  3.5:'Asia/Tehran',
  4:'Asia/Baku',
  4.5:'Asia/Kabul',
  5:'Antarctica/Mawson',
  5.5:'Asia/Calcutta',
  5.75:'Asia/Kathmandu',
  6:'Asia/Bishkek',
  6.5:'Asia/Rangoon',
  7:'Asia/Hovd',
  8:'Asia/Hong_Kong',
  8.75:'Australia/Eucla',
  9:'Asia/Dili',
  9.5:'Australia/Adelaide',
  10:'Asia/Vladivostok',
  10.5:'Australia/Lord_Howe',
  11:'Pacific/Bougainville',
  12:'Pacific/Fiji',
  13:'Pacific/Kanton',
  13.75:'Pacific/Chatham',
  14:'Pacific/Kiritimati',
}

export const ianaTzCodeWest = {
  1:'Atlantic/Cape_Verde',
  2:'America/Noronha',
  2.5:'America/St_Johns',
  3:'America/Catamarca',
  4:'America/Caracas',
  5:'America/Cancun',
  6:'America/Costa_Rica',
  7:'America/Creston',
  8:'Pacific/Pitcairn',
  9:'Pacific/Gambier',
  9.5:'Pacific/Marquesas',
  10:'Pacific/Honolulu',
  11:'Pacific/Midway',
}

export enum ianaTzArea {
  Africa,
  America,
  Asia,
  Europe,
  Pacific,
  Indian,
  Antarctica,
  Atlantic,
  Australia,
  Arctic,
}

export const ianaTzCode = {
  0:'Abidjan,Accra,Addis_Ababa,Algiers,Asmara,Asmera,Bamako,Bangui,Banjul,Bissau,Blantyre,Brazzaville,Bujumbura,Cairo,Casablanca,Ceuta,Conakry,Dakar,Dar_es_Salaam,Djibouti,Douala,El_Aaiun,Freetown,Gaborone,Harare,Johannesburg,Juba,Kampala,Khartoum,Kigali,Kinshasa,Lagos,Libreville,Lome,Luanda,Lubumbashi,Lusaka,Malabo,Maputo,Maseru,Mbabane,Mogadishu,Monrovia,Nairobi,Ndjamena,Niamey,Nouakchott,Ouagadougou,Porto_Novo,São_Tomé,Timbuktu,Tripoli,Tunis,Windhoek,Saint_Helena',
  1:'Adak,Anchorage,Anguilla,Antigua,Araguaina,Buenos_Aires,Catamarca,Comodoro_Rivadavia,Cordoba,La_Rioja,Rio_Gallegos,Salta,San_Juan,San_Luis,Tucuman,Ushuaia,Aruba,Asuncion,Atikokan,Atka,Bahia,Bahia_Banderas,Barbados,Belem,Belize,Blanc-Sablon,Boa_Vista,Bogota,Boise,Cambridge_Bay,Campo_Grande,Cancun,Caracas,Catamarca,Cayenne,Cayman,Chicago,Chihuahua,Ciudad_Juarez,Coral_Harbour,Cordoba,Costa_Rica,Creston,Cuiaba,Curacao,Danmarkshavn,Dawson,Dawson_Creek,Denver,Detroit,Dominica,Edmonton,Eirunepe,El_Salvador,Ensenada,Fort_Nelson,Fort_Wayne,Fortaleza,Glace_Bay,Godthab,Goose_Bay,Grand_Turk,Grenada,Guadeloupe,Guatemala,Guayaquil,Guyana,Halifax,Havana,Hermosillo,Indianapolis,Knox,Marengo,Petersburg,Tell_City,Vevay,Vincennes,Winamac,Indianapolis,Inuvik,Iqaluit,Jamaica,Jujuy,Juneau,Louisville,Monticello,Knox,Kralendijk,La_Paz,Lima,Los_Angeles,Lower_Princes,Maceio,Managua,Manaus,Marigot,Martinique,Matamoros,Mazatlan,Mendoza,Menominee,Merida,Metlakatla,Mexico_City,Miquelon,Moncton,Monterrey,Montevideo,Montreal,Montserrat,Nassau,New_York,Nipigon,Nome,Noronha,Beulah,New_Salem,Nuuk,Ojinaga,Panama,Pangnirtung,Paramaribo,Phoenix,Port-au-Prince,Port_of_Spain,Porto_Acre,Porto_Velho,Puerto_Rico,Punta_Arenas,Rainy_River,Rankin_Inlet,Recife,Regina,Resolute,Rio_Branco,Rosario,Santa_Isabel,Santarem,Santiago,Santo_Domingo,Sao_Paulo,Scoresbysund,Shiprock,Sitka,St_Barthelemy,St_Johns,St_Kitts,St_Lucia,St_Thomas,St_Vincent,Swift_Current,Tegucigalpa,Thule,Thunder_Bay,Tijuana,Toronto,Tortola,Vancouver,Virgin,Whitehorse,Winnipeg,Yakutat,Yellowknife',
  2:'Aden,Almaty,Amman,Anadyr,Aqtau,Aqtobe,Ashgabat,Ashkhabad,Atyrau,Baghdad,Bahrain,Baku,Bangkok,Barnaul,Beirut,Bishkek,Brunei,Calcutta,Chita,Choibalsan,Chongqing,Chungking,Colombo,Dacca,Damascus,Dhaka,Dili,Dubai,Dushanbe,Famagusta,Gaza,Harbin,Hebron,Ho_Chi_Minh,Hong_Kong,Hovd,Irkutsk,Istanbul,Jakarta,Jayapura,Jerusalem,Kabul,Kamchatka,Karachi,Kashgar,Kathmandu,Katmandu,Khandyga,Kolkata,Krasnoyarsk,Kuala_Lumpur,Kuching,Kuwait,Macao,Macau,Magadan,Makassar,Manila,Muscat,Nicosia,Novokuznetsk,Novosibirsk,Omsk,Oral,Phnom_Penh,Pontianak,Pyongyang,Qatar,Qostanay,Qyzylorda,Rangoon,Riyadh,Saigon,Sakhalin,Samarkand,Seoul,Shanghai,Singapore,Srednekolymsk,Taipei,Tashkent,Tbilisi,Tehran,Tel_Aviv,Thimbu,Thimphu,Tokyo,Tomsk,Ujung_Pandang,Ulaanbaatar,Ulan_Bator,Urumqi,Ust-Nera,Vientiane,Vladivostok,Yakutsk,Yangon,Yekaterinburg,Yerevan',
  3:'Amsterdam,Andorra,Astrakhan,Athens,Belfast,Belgrade,Berlin,Bratislava,Brussels,Bucharest,Budapest,Busingen,Chisinau,Copenhagen,Dublin,Gibraltar,Guernsey,Helsinki,Isle_of_Man,Istanbul,Jersey,Kaliningrad,Kiev,Kirov,Kyiv,Lisbon,Ljubljana,London,Luxembourg,Madrid,Malta,Mariehamn,Minsk,Monaco,Moscow,Nicosia,Oslo,Paris,Podgorica,Prague,Riga,Rome,Samara,San_Marino,Sarajevo,Saratov,Simferopol,Skopje,Sofia,Stockholm,Tallinn,Tirane,Tiraspol,Ulyanovsk,Uzhgorod,Vaduz,Vatican,Vienna,Vilnius,Volgograd,Warsaw,Zagreb,Zaporozhye,Zurich',
  4:'Apia,Auckland,Bougainville,Chatham,Chuuk,Easter,Efate,Enderbury,Fakaofo,Fiji,Funafuti,Galapagos,Gambier,Guadalcanal,Guam,Honolulu,Johnston,Kanton,Kiritimati,Kosrae,Kwajalein,Majuro,Marquesas,Midway,Nauru,Niue,Norfolk,Noumea,Pago_Pago,Palau,Pitcairn,Pohnpei,Ponape,Port_Moresby,Rarotonga,Saipan,Samoa,Tahiti,Tarawa,Tongatapu',
  5:'Antananarivo,Chagos,Christmas,Cocos,Comoro,Kerguelen,Mahé,Maldives,Mauritius',
  6:"Casey,Davis,DumontDUrville,Macquarie,Mawson,McMurdo,Palmer,Rothera,Syowa,Troll,Vostok,South_Pole",
  7:'Azores,Bermuda,Canary,Cape_Verde,Faeroe,Faroe,Jan Mayen,Madeira,Reykjavik,South_Georgia,St_Helena,Stanley',
  8:'Adelaide,Brisbane,Broken_Hill,Canberra,Currie,Darwin,Eucla,Hobart,Lindeman,Lord_Howe,Melbourne,Perth,Queensland,Sydney,Tasmania,Victoria,Yancowinna',
  9:'Longyearbyen',
}
