name: Publish Package to npmjs
'on':
  push:
    branches:
      - release
jobs:
  publish:
    name: publish package task
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
